name: Security Datalake - ExpertsLiveEU

pr: none

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: MicrosoftSentinel
    variables:
      - template: parameters/environment-variables-${{ parameters.env }}.yml
    # Branch is master or environment is nonprd
    condition:  or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith('${{ parameters.env }}', 'nonprd'))

    displayName: 'Microsoft Sentinel "${{ parameters.env }}"'
    jobs:
      - job: azureSentinelWeUJob
        displayName: 'Microsoft Sentinel'
        steps:
          # Retrieve Service Connection credentials
          - template: templates/get-service-connection-credentials.yml
            parameters:
              serviceconnection_name: ${{ variables.serviceConnection }}