name: Security Datalake - ExpertsLiveEU

pr: none

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: MicrosoftSentinel
    displayName: 'Microsoft Sentinel'
    jobs:
      - job: azureSentinelWeUJob
        displayName: 'Deploy workspace'
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'Deploy workspace'
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'Visual Studio Enterprise'
            subscriptionId: '412f40b6-0a47-4dcc-80a4-17fc5c679c0e'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'rg-sentinel-01'
            location: 'West US 3'
            templateLocation: 'Linked artifact'
            csmFile: 'templates/sentinelworkspace.json'
            csmParametersFile: 'parameters/law-sentinel-01.parameters.json'
            deploymentMode: 'Incremental'