name: Security Datalake - ExpertsLiveEU

pr: none

trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscriptionId: '412f40b6-0a47-4dcc-80a4-17fc5c679c0e'

stages:
  - stage: MicrosoftSentinel
    displayName: 'Microsoft Sentinel'
    jobs:
      - job: azureSentinelWeUJob
        displayName: 'Deploy workspace'
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          displayName: 'Create or Update Resource Group'
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'Visual Studio Enterprise'
            subscriptionId: $(subscriptionId)
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'rg-sentinel-01'
            location: 'West US 3'
            templateLocation: 'Linked artifact'
            csmFile: 'templates/sentinelworkspace.json'
            csmParametersFile: 'parameters/law-sentinel-01.parameters.json'
            deploymentMode: 'Incremental'
        - task: AzurePowerShell@5
          displayName: 'Run table-level transformations (a.k.a. Spl1tR)'
          inputs:
            azureSubscription: 'Visual Studio Enterprise'
            ScriptType: 'FilePath'
            ScriptPath: 'scripts/spl1tr.ps1'
            ScriptArguments: '-SubscriptionId "412f40b6-0a47-4dcc-80a4-17fc5c679c0e" -WorkspaceName "law-sentinel-01" -PathToYamlFiles "../parameters/transformations/" -ResourceGroupName "rg-sentinel-01" -SaveTemplate'
            errorActionPreference: 'continue'
            azurePowerShellVersion: 'LatestVersion'
            pwsh: true